[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn run build:shared", "cd apps/backend && yarn run build"]

[start]
cmd = "cd apps/backend && node dist/server.js"
